# Generated by Django 4.1.3 on 2022-11-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_usuarios_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('saldo', models.FloatField(default=0)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.instituicao')),
            ],
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.conta'),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
