# Generated by Django 4.1.3 on 2022-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_conta_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
