# Generated by Django 4.1.3 on 2022-12-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_conta_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destinatario', to='Account.conta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origem', to='Account.conta'),
        ),
    ]
