version: '3'

services:
  app:
    image: "appdjango"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_NAME=appdjango
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=12345
    depends_on:
      - db
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=db
